# Generated by Django 5.0.4 on 2024-04-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_locatorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipologradouro',
            old_name='tipo_logadouro',
            new_name='tipo_logradouro',
        ),
    ]
