# Generated by Django 5.0.4 on 2024-04-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_tipo_logadouro_tipologradouro_tipo_logradouro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='nome_logradouro',
        ),
    ]
